recipe: default.v1
language: en
assistant_id: saleor_assistant_min

pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      model_group: openai-direct
    # prompt: prompts/command-generator.jinja2

policies:
  - name: FlowPolicy
